### PR TITLE
Compatibility with Redmine 4

### PR DESCRIPTION
**Pull request by sparunakian**
Hi,

This MR makes the plugin compatible with Redmine 4.1. There may still be some incompatibilities, but the mail sending part works.

Regards,

### CODE REVIEW

**Comment by hhokawa777** [comment]
Thank you so much for your PR! I will try to merge your code.

I tried version for redmine v4 ago, but I couldn't get confidence that time because my test code showed some strange behaviors and I knew a way of mailing changed a lot from v4. Could you let me know if your code already experienced production environment without any issues?

**Comment by sparunakian** [comment]
Yes, this code is in production and there is no blocking issue identified. Files are sent without any problem. However, there is deprecation warnings in the logs:

```
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /path/to/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /path/to/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /path/to/redmine/config/routes.rb:370)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /path/to/redmine/config/routes.rb:370)
```

More work will be needed for the plugin to work with Redmine 5.0/Rails 6.0.

**Comment by hhokawa777** [comment]
Thank you so much for your confirmation!
I merged your code into temp branch for some work before release.

**Comment by sparunakian** [comment]
Thank you for merging!

**Pull request merged**
